"""add_citation_snapshot_to_version

Revision ID: 0bbdce140537
Revises: 7b42c81b0fe7
Create Date: 2026-05-15 11:18:22.985017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbdce140537'
down_revision = '7b42c81b0fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_author_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('original_resource_title', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('resource_version_parent_version_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'resource_version', ['parent_version_id'], ['version_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_version', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('resource_version_parent_version_id_fkey'), 'resource_version', ['parent_version_id'], ['version_id'])
        batch_op.drop_column('original_resource_title')
        batch_op.drop_column('original_author_name')

    # ### end Alembic commands ###
