"""add token to verification_codes

Revision ID: 3457ae35c40f
Revises: 3ae047a88c5d
Create Date: 2026-05-07 04:23:15.288037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3457ae35c40f'
down_revision = '3ae047a88c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_verification_codes_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_token'))
        batch_op.drop_column('token')

    # ### end Alembic commands ###
