"""add_collaborators_and_resource_settings

Revision ID: 394bd0339f0f
Revises: bb07c60d444f
Create Date: 2026-05-07 21:01:17.927903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394bd0339f0f'
down_revision = 'bb07c60d444f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['resource_collection.collection_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_remixing', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('collaboration_mode', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_collection', schema=None) as batch_op:
        batch_op.drop_column('collaboration_mode')
        batch_op.drop_column('visibility')
        batch_op.drop_column('allow_remixing')

    op.drop_table('resource_collaborators')
    # ### end Alembic commands ###
