"""add username to teachers

Revision ID: 3ae047a88c5d
Revises: ebc8485568e8
Create Date: 2026-05-07 03:33:05.378083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae047a88c5d'
down_revision = 'ebc8485568e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column as nullable first
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))

    # 2. Backfill existing users with 'user_{id}'
    op.execute("UPDATE teachers SET username = 'user_' || teacher_id WHERE username IS NULL")

    # 3. Now set it to NOT NULL and create the unique index
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False)
        batch_op.create_index(batch_op.f('ix_teachers_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
