"""add_original_author_username_and_unique_title

Revision ID: 56dd7097c566
Revises: 0bbdce140537
Create Date: 2026-05-15 12:04:36.753988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56dd7097c566'
down_revision = '0bbdce140537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_collection', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['title'])

    with op.batch_alter_table('resource_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_author_username', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_version', schema=None) as batch_op:
        batch_op.drop_column('original_author_username')

    with op.batch_alter_table('resource_collection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
