"""add_is_published_and_visibility_to_version

Revision ID: 8d851af2dd72
Revises: ac30dbd5fd3f
Create Date: 2026-05-15 01:20:04.317326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d851af2dd72'
down_revision = 'ac30dbd5fd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), server_default='public', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_version', schema=None) as batch_op:
        batch_op.drop_column('visibility')
        batch_op.drop_column('is_published')
    # ### end Alembic commands ###
