"""add_duration_collab_remix_to_version

Revision ID: 9c15d2ce3787
Revises: 8d851af2dd72
Create Date: 2026-05-15 01:29:39.790381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c15d2ce3787'
down_revision = '8d851af2dd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimate_duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('allow_remixing', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('collaboration_mode', sa.String(length=20), server_default='none', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_version', schema=None) as batch_op:
        batch_op.drop_column('collaboration_mode')
        batch_op.drop_column('allow_remixing')
        batch_op.drop_column('estimate_duration')
    # ### end Alembic commands ###
