"""add estimate_duration to resource_collection

Revision ID: 9d2552c94a91
Revises: 8e8f75f087ba
Create Date: 2026-05-07 10:51:34.119696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2552c94a91'
down_revision = '8e8f75f087ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimate_duration', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_collection', schema=None) as batch_op:
        batch_op.drop_column('estimate_duration')

    # ### end Alembic commands ###
