"""fix: enum error

Revision ID: a5b6ee52b420
Revises: db70868bf46d
Create Date: 2026-04-20 01:14:43.915334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b6ee52b420'
down_revision = 'db70868bf46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))

    with op.batch_alter_table('user_auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=False))
        batch_op.alter_column('hashed_password',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_auth', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('hashed_password',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('google_id')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
