"""Add bio, role, institution to Teacher model

Revision ID: a7f055fad3c1
Revises: 3af4feba95b1
Create Date: 2026-05-04 00:16:10.307335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f055fad3c1'
down_revision = '3af4feba95b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('institution', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('institution')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
