"""add download_count to resource_collection

Revision ID: a849b5f23ea8
Revises: d100e8e7364f
Create Date: 2026-05-06 22:59:44.373161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a849b5f23ea8'
down_revision = 'd100e8e7364f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_collection', schema=None) as batch_op:
        batch_op.drop_column('download_count')

    # ### end Alembic commands ###
