"""add student summary field

Revision ID: ac30dbd5fd3f
Revises: 37da86f81d5c
Create Date: 2026-05-08 14:30:17.758516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac30dbd5fd3f'
down_revision = '8a20b61f9921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_collection', schema=None) as batch_op:
        batch_op.drop_column('student_summary')

    # ### end Alembic commands ###
