"""add is_archived to teacher

Revision ID: af33a6fed9db
Revises: 3574c2eadff5
Create Date: 2026-05-16 02:05:36.079802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af33a6fed9db'
down_revision = '3574c2eadff5'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add the column as nullable first
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # 2. Set default value for existing rows
    op.execute("UPDATE teachers SET is_archived = FALSE")

    # 3. Alter column to be NOT NULL
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('is_archived', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
