"""add_file_signatures_table

Revision ID: b7d683d36c6c
Revises: cec3aef51569
Create Date: 2026-05-08 00:55:41.885031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d683d36c6c'
down_revision = 'cec3aef51569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_signatures_file_hash'), ['file_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_signatures_file_hash'))

    op.drop_table('file_signatures')
    # ### end Alembic commands ###
