"""add_settings_fields_to_teacher

Revision ID: bb07c60d444f
Revises: 9d2552c94a91
Create Date: 2026-05-07 19:33:28.395680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb07c60d444f'
down_revision = '9d2552c94a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=20), server_default='system', nullable=False))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('push_notifications', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_profile_public', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('show_email_on_profile', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('show_email_on_profile')
        batch_op.drop_column('is_profile_public')
        batch_op.drop_column('push_notifications')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###
