"""add_file_hash_to_resource_file

Revision ID: cec3aef51569
Revises: 394bd0339f0f
Create Date: 2026-05-08 00:42:04.902211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec3aef51569'
down_revision = '394bd0339f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_resource_file_file_hash'), ['file_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_file_file_hash'))
        batch_op.drop_column('file_hash')

    # ### end Alembic commands ###
