"""Initial clean schema with server defaults

Revision ID: db0d81466d03
Revises: 
Create Date: 2026-03-16 01:11:27.770631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0d81466d03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_type',
    sa.Column('content_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('content_type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('grade_level',
    sa.Column('grade_level_id', sa.Integer(), nullable=False),
    sa.Column('grade_name', sa.String(length=30), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('grade_level_id')
    )
    op.create_table('subject',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=240), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('subject_name')
    )
    op.create_table('tag_type',
    sa.Column('tag_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tag_type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('joined_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('resource_collection',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_level_id', sa.Integer(), nullable=False),
    sa.Column('content_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_type.content_type_id'], ),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_level.grade_level_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['teachers.teacher_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], ),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=50), nullable=False),
    sa.Column('tag_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_type_id'], ['tag_type.tag_type_id'], ),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('user_auth',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('auth_id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_table('resource_tag',
    sa.Column('resource_tag_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['resource_collection.collection_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('resource_tag_id'),
    sa.UniqueConstraint('collection_id', 'tag_id', name='_collection_tag_uc')
    )
    op.create_table('review',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('review_by', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['collection_id'], ['resource_collection.collection_id'], ),
    sa.ForeignKeyConstraint(['review_by'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('resource_tag')
    op.drop_table('user_auth')
    op.drop_table('tag')
    op.drop_table('resource_collection')
    op.drop_table('teachers')
    op.drop_table('tag_type')
    op.drop_table('subject')
    op.drop_table('grade_level')
    op.drop_table('content_type')
    # ### end Alembic commands ###
