"""add resource_version and resource_file tables

Revision ID: db70868bf46d
Revises: db0d81466d03
Create Date: 2026-03-22 21:59:20.694604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db70868bf46d'
down_revision = 'db0d81466d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_version',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('is_remix', sa.Boolean(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['resource_collection.collection_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['teachers.teacher_id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['resource_version.version_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('resource_file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['resource_version.version_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_file')
    op.drop_table('resource_version')
    # ### end Alembic commands ###
