"""add user_activities table

Revision ID: ebc8485568e8
Revises: 4e91bc7b3fcb
Create Date: 2026-05-07 02:15:19.474270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc8485568e8'
down_revision = '4e91bc7b3fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['resource_collection.collection_id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['teachers.teacher_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activities')
    # ### end Alembic commands ###
